export interface ESTUDIANTE{
    ID_PERSONA : number;
    NOMBRE : string;
    APELLIDO : string;
    CORREO : string;
    CEDULA : number;   
    ROL_ID_ROL : number;
    ID_USUARIO : number;    
    CELULAR : string;
    EDAD : number;
    ESTATURA : number;
    PESO : number;
    RH : string;
    EPS : string;
    DIFICULTADES_PATOLOGICAS : string;
    FECHA_NACIMIENTO: string;
    NOMBRE_ACOMPANANTE: string;
    CELULAR_ACOMPANANTE: string;
    PARENTESCO_ACOMPANANTE: string;
    ID_ESTUDIANTE: number;
    CODIGO: number;
    SEMESTRE: number;
    UUSUARIO_ID_USUARIO: number;
    FACULTAD_ID_FACULTAD: number;
}