export interface ESTUDIANTE{
    Id_persona : number;
    Nombre : string;
    Apellido : string;
    Correo : string;
    Cedula : number; 
    Rutina_asignada: any;  
    Rol_id_rol : number;
    Id_usuario : number;    
    Celular : string;
    Edad : number;
    Estatura : number;
    Peso : number;
    Rh : string;
    Eps : string;
    Deportista : string;
    Dificultades_patologicas : string;
    EscalaPeso : string;
    Fecha_nacimiento: string;
    Nombre_Acompanante: string;
    Celular_Acompanante: string;
    Parentesco_Acompanante: string;
    Id_estudiante: number;
    Codigo: number;
    Semestre: number;
    Usuario_id_usuario: number;
    Facultad_id_facultad: number;
}